import { Button } from "@/components/ui/button";
import Rain from "@/components/Rain/Rain";
import ExampleList from "@/components/ExampleList";


import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Raink",
  description: "Generated by create next app",
};



export default function Home() {


  return (
    <main className="flex min-h-screen flex-col items-center justify-between py-24">
      <Rain />
      <ExampleList />
    </main>
  );
}
